import type { Metadata } from "next";

import "./globals.css";
import { inter } from "./ui/fonts";

export const metadata: Metadata = {
  title: "Ding-clone app ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<html lang="en" data-lt-installed="true" suppressHydrationWarning={true} className="scroll-smooth">
      <body className={`${inter.className}   antialiased`}>{children}</body>
    </html>
  );
}
